spring:
  application:
    name: "task-manager-be-ms"
  profiles:
    active: dev

  cloud:
    config:
      enabled: true

  config:
    import: optional:configserver:http://localhost:8071/


  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"